/**
 * Represents the source of the outfit, whether it was created by a user or generated by AI.
 */
export type OutfitSource = 'user' | 'ai';

/**
 * Represents the seasons for which the outfit is suitable.
 */
export type OutfitSeason = 'spring' | 'summer' | 'fall' | 'winter';

/**
 * Main interface for an outfit, representing a collection of wardrobe items.
 */
export interface Outfit {
  /**
   * Unique identifier for the outfit.
   * @example "outfit-12345-abcde"
   */
  id: string;

  /**
   * The ID of the user who owns this outfit.
   */
  userId: string;

  /**
   * The name of the outfit.
   * @example "週末約會穿搭"
   */
  name: string;

  /**
   * An optional description for the outfit.
   * @example "輕鬆休閒風格，適合戶外活動。"
   */
  description?: string;

  /**
   * An array of wardrobe item IDs that make up the outfit.
   * Must contain at least one item ID.
   */
  itemIds: string[];

  /**
   * User-defined tags for custom categorization.
   * @example ['約會', '春季', '戶外']
   */
  tags?: string[];

  /**
   * The occasion for which the outfit is suitable.
   * @example "約會"
   */
  occasion?: string;

  /**
   * The season for which the outfit is most appropriate.
   */
  season?: OutfitSeason;

  /**
   * An optional URL for an image of the complete outfit.
   */
  imageUrl?: string;

  /**
   * The source of the outfit's creation.
   */
  source?: OutfitSource;

  /**
   * A user-provided rating for the outfit, on a scale of 1 to 5.
   * @minimum 1
   * @maximum 5
   */
  rating?: number;

  /**
   * The timestamp when the outfit was created.
   */
  createdAt: Date;

  /**
   * The timestamp when the outfit was last updated.
   */
  updatedAt?: Date;
}

/**
 * Data Transfer Object for creating a new outfit.
 * Excludes server-generated fields like id, createdAt, and updatedAt.
 */
export type CreateOutfitDto = Omit<Outfit, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Data Transfer Object for updating an existing outfit.
 * All fields are optional, and immutable fields cannot be changed.
 */
export type UpdateOutfitDto = Partial<Omit<Outfit, 'id' | 'userId' | 'createdAt' | 'updatedAt'>>;